#!/bin/sh
NAME=sepiida-agent
USER=sepiida-agent
HOME=/var/lib/$NAME

set -e
case "$1" in
    configure)
        if ! id $USER > /dev/null 2>&1; then
            echo Creating $USER user...
            adduser --quiet --system --ingroup nogroup \
                --home $HOME --shell /usr/bin/sepiida-agent-connect $USER
            mkdir -p /etc/sepiida
            install -d -o sepiida-agent -g root -m 750 $HOME/.ssh
            [ -e $HOME/.ssh/authorized_keys  ] || install -o sepiida-agent -g root -m 640 /dev/null $HOME/.ssh/authorized_keys
        fi

        conf=/etc/sepiida/agent.conf
        if [ -e $conf ] && \
        ! egrep -q '^[[:space:]]*resolve[[:space:]]+ips[[:space:]]*=' $conf
        then
            # add "resolve ips = False" after "log debug =" line
            sed -i '/^[[:space:]]*log[[:space:]][[:space:]]*debug[[:space:]][[:space:]]*=/a \
# Whether to resolve client IP addresses (e.g. LTSP client)\
resolve ips = False' $conf
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        ;;
esac

#DEBHELPER#

exit 0
